Photo.create!([
  {resort_id: 1, user_id: 1, url: "http://res.cloudinary.com/dagjelvab/image/upload/v1489734590/vail1.jpg", caption: nil},
  {resort_id: 1, user_id: 1, url: "http://res.cloudinary.com/dagjelvab/image/upload/v1489734637/vail2.jpg", caption: nil},
  {resort_id: 1, user_id: 1, url: "http://res.cloudinary.com/dagjelvab/image/upload/v1489734676/vail3.jpg", caption: nil},
  {resort_id: 1, user_id: 1, url: "http://res.cloudinary.com/dagjelvab/image/upload/v1489734720/vail4.jpg", caption: nil},
  {resort_id: 2, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490262750/hgandg5purdl0rqhgiyt.jpg", caption: nil},
  {resort_id: 2, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490262798/olpz80iaatpbt16kncp3.jpg", caption: nil},
  {resort_id: 2, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490262810/ozzrh0oexciybzancetv.jpg", caption: nil},
  {resort_id: 2, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490262819/vmc4cxs9rlcehmm0czyq.jpg", caption: nil},
  {resort_id: 4, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490262963/fnh9ehhnk9e9snlk4qki.jpg", caption: nil},
  {resort_id: 4, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490262981/wm1bhzzqk4mznysqq27q.jpg", caption: nil},
  {resort_id: 4, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490262992/lvntpinzl7bgyqhpey6u.jpg", caption: nil},
  {resort_id: 4, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263005/nxua7hzepldwzrgumvay.jpg", caption: nil},
  {resort_id: 5, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263117/zoxmszyebckcq8onpxfp.jpg", caption: nil},
  {resort_id: 5, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263131/qx2ucq61uuboiba6ptww.jpg", caption: nil},
  {resort_id: 5, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263152/in3lexssblruewchesbj.jpg", caption: nil},
  {resort_id: 5, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263229/armuapunigpvd7i8wgme.jpg", caption: nil},
  {resort_id: 6, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263335/fwkysny4tid2x0zx8qud.jpg", caption: nil},
  {resort_id: 6, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263340/qoo0pm5wygkt5zmntyux.jpg", caption: nil},
  {resort_id: 6, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263344/zuluvdyglsykvwy8yk6i.jpg", caption: nil},
  {resort_id: 6, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263348/zmeav18hnbzh04innpdd.jpg", caption: nil},
  {resort_id: 7, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263421/nqiihqxvnu93yllapvmc.jpg", caption: nil},
  {resort_id: 7, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263427/uhq3psafsvxv6usxictd.jpg", caption: nil},
  {resort_id: 7, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263432/s1waavrcp1o2b3sv1zqn.jpg", caption: nil},
  {resort_id: 8, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263520/xwddpgd0ugxevde9ru4m.jpg", caption: nil},
  {resort_id: 8, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263526/e6fkkbw7gfgd1nrtyagh.jpg", caption: nil},
  {resort_id: 8, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263532/s6tas9hipbbjx44n7grk.jpg", caption: nil},
  {resort_id: 8, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263537/ojtzbt6kv50con58irei.jpg", caption: nil},
  {resort_id: 9, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263648/rp2xozuvv5l1wmom3yon.jpg", caption: nil},
  {resort_id: 9, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263654/yrmwtmbwabld7y7u7gxr.jpg", caption: nil},
  {resort_id: 9, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490263660/jvnfg7fzacui3pawi3dn.webp", caption: nil},
  {resort_id: 10, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264311/nmhds4oqn1ix0snwfafn.jpg", caption: nil},
  {resort_id: 10, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264319/g5atyjnzu5erab6yxynn.jpg", caption: nil},
  {resort_id: 10, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264325/lqklh3demzygicvsivdn.jpg", caption: nil},
  {resort_id: 11, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264427/weh3rpoij4k0m9rec918.jpg", caption: nil},
  {resort_id: 11, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264433/zoosz1k2ow0z6nxb6d5f.jpg", caption: nil},
  {resort_id: 11, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264438/qp91u0pbo4nl3yt3t5cc.jpg", caption: nil},
  {resort_id: 11, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264444/grqlldhelc0ngbrixwlu.jpg", caption: nil},
  {resort_id: 12, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264508/z11fk99xpqwdfukxi3og.jpg", caption: nil},
  {resort_id: 12, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264516/njaddwfyutwsbtc8r0ib.jpg", caption: nil},
  {resort_id: 12, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264527/eugiijbnyblm7ydlma4l.jpg", caption: nil},
  {resort_id: 13, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264631/ezuqdhlu7jw8bjrmt2nr.jpg", caption: nil},
  {resort_id: 13, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264638/dx5loihv1r33baalbusu.jpg", caption: nil},
  {resort_id: 13, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264643/wnz61t7l5r09mpesnevk.jpg", caption: nil},
  {resort_id: 14, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264723/vkl0aq18p7glctnbnrq2.jpg", caption: nil},
  {resort_id: 14, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264729/mscl995ty9gmkgrq4p5p.jpg", caption: nil},
  {resort_id: 14, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264734/avpnrqtuzlcui0z1d4yp.jpg", caption: nil},
  {resort_id: 15, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264789/cfschgdny3td04omxlcs.jpg", caption: nil},
  {resort_id: 15, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264834/dxc7tz3t07fwso5gqddp.jpg", caption: nil},
  {resort_id: 15, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264846/w3eds363uvnhp26fiirq.jpg", caption: nil},
  {resort_id: 16, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264940/kif3mjaaua2skrscjd95.jpg", caption: nil},
  {resort_id: 16, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264947/umbk835rlq6fwlnwoj4s.jpg", caption: nil},
  {resort_id: 16, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264951/mhurq7unqrbivqv3yove.jpg", caption: nil},
  {resort_id: 16, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490264957/jsmqqnopdmlzchg4jx9a.jpg", caption: nil},
  {resort_id: 17, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490265030/omyfodins8u46hwyigcn.jpg", caption: nil},
  {resort_id: 17, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490265034/zfll4fclpi6s0gzsu0i7.jpg", caption: nil},
  {resort_id: 17, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490265040/edrftdvjs7nkyc5tyxgd.jpg", caption: nil},
  {resort_id: 18, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490265166/tfv8jmkm85u2nvsbzeqh.jpg", caption: nil},
  {resort_id: 18, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490265177/vsoz7oagxh1mmztp9dpg.jpg", caption: nil},
  {resort_id: 19, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490265292/a8fhfsgzbsnnrywgny4w.jpg", caption: nil},
  {resort_id: 3, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490265330/fyy4sq8rdc3in0qa0nb7.jpg", caption: nil},
  {resort_id: 3, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490265589/uarue2g2be3mdydcfvuu.jpg", caption: nil},
  {resort_id: 18, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490265184/izncqbflew3jrld6aa3d.jpg", caption: nil},
  {resort_id: 19, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490265273/p4bowcvwcwokofpzmia1.jpg", caption: nil},
  {resort_id: 3, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490265576/y4nsgkiiddeu8kflofel.jpg", caption: nil},
  {resort_id: 18, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490265190/hkst5sxvtcqdjcm8ifma.jpg", caption: nil},
  {resort_id: 19, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490265284/xkpxeef5it2afdmtay8p.jpg", caption: nil},
  {resort_id: 3, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490265566/rw6nweufpmnevxprihmv.jpg", caption: nil},
  {resort_id: 3, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490265598/mtruayhnzzdpcqe3h91d.jpg", caption: nil},
  {resort_id: 6, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490376374/fpmhnpzkpn40beae1qoc.jpg", caption: nil},
  {resort_id: 54, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490379503/oflhzt1bytynoyntx4z1.jpg", caption: nil},
  {resort_id: 53, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490379673/qertgaijrufdjknpo675.jpg", caption: nil},
  {resort_id: 53, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490379683/rzl0tvmwu6i9wemykpm9.jpg", caption: nil},
  {resort_id: 53, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490379694/nexehpbggeipwtzlrkap.jpg", caption: nil},
  {resort_id: 52, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490380028/h96qh2nchcvusxgbdpn8.jpg", caption: nil},
  {resort_id: 52, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490380035/ynbimr99f8mbyueuegle.jpg", caption: nil},
  {resort_id: 52, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490380041/brbplypxzfg1cnct4iem.jpg", caption: nil},
  {resort_id: 51, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490380251/dbkbqovtyk4s4ginzotk.jpg", caption: nil},
  {resort_id: 51, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490380258/fylyxxi5pcigqxtb4nze.jpg", caption: nil},
  {resort_id: 51, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490380265/guylkpbrzegtdmlnlwya.jpg", caption: nil},
  {resort_id: 50, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490380432/vxhm6akhvl12cgvzlzm5.jpg", caption: nil},
  {resort_id: 50, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490380441/se4i9nncprku5t3uwlaz.jpg", caption: nil},
  {resort_id: 49, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490380787/ph8zrdz76tqbghwzlrwu.jpg", caption: nil},
  {resort_id: 49, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490380795/tnxju4dzkb0w6j3mgyfd.jpg", caption: nil},
  {resort_id: 49, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490380828/xo0oon7djqp3x6k8yet4.jpg", caption: nil},
  {resort_id: 48, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490381042/yjnnh0sickwlg0peojd1.jpg", caption: nil},
  {resort_id: 48, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490381048/pbw2eftf8nskwdoajs5v.jpg", caption: nil},
  {resort_id: 47, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490381237/ginta3s6wkls27vc9bax.jpg", caption: nil},
  {resort_id: 47, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490381244/txmmtjq8u8ypaqqkm2la.jpg", caption: nil},
  {resort_id: 47, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490381253/lrgfxxpmuyqo89bneyp2.jpg", caption: nil},
  {resort_id: 46, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490381487/ezmpeowqoiqtpeepywqi.jpg", caption: nil},
  {resort_id: 46, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490381492/listy42m9q6lyucuqfco.jpg", caption: nil},
  {resort_id: 45, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490381628/cix0u8535ygv6kkqboen.jpg", caption: nil},
  {resort_id: 45, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490381633/zp0d0hl7xhuvxnqwlete.jpg", caption: nil},
  {resort_id: 45, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490381642/ry7x8k4g5mdgxyxfdtsb.jpg", caption: nil},
  {resort_id: 44, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490381752/lfpeameyfsc1lzbrjvrz.jpg", caption: nil},
  {resort_id: 44, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490381763/zchnzxdwwxrc91bq1wif.jpg", caption: nil},
  {resort_id: 43, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490382098/qirffzi4rpukfzou0oym.jpg", caption: nil},
  {resort_id: 41, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490382449/ekmdpqaah2ghqdauzcy5.jpg", caption: nil},
  {resort_id: 39, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490382792/ux7zribja0ijccokxuxc.jpg", caption: nil},
  {resort_id: 43, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490381958/fijywurchoezo6fayru6.jpg", caption: nil},
  {resort_id: 42, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490382304/qrnqaj5dgl4gtx7itwdm.jpg", caption: nil},
  {resort_id: 40, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490382586/tzj4ryngrj9xn8ueodo5.jpg", caption: nil},
  {resort_id: 39, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490382796/djfw6gyofrc0hjnty3hm.jpg", caption: nil},
  {resort_id: 42, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490382295/indudyiqzwobhdgshyro.jpg", caption: nil},
  {resort_id: 41, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490382437/r0iuw7nisejkbp1lv4c3.jpg", caption: nil},
  {resort_id: 40, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490382581/vpe7tgbhowinhch6a0fg.webp", caption: nil},
  {resort_id: 39, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490382787/grnysel29yfate0xopuy.jpg", caption: nil},
  {resort_id: 43, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490381972/suo8hptbgxzpyfdchhmg.jpg", caption: nil},
  {resort_id: 42, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490382299/qu24ur3kcosqykox61pj.jpg", caption: nil},
  {resort_id: 41, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490382443/uw1bsf050rs0wvekhdla.jpg", caption: nil},
  {resort_id: 40, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490382593/eyn9kumjkcbfpi3b5rh7.jpg", caption: nil},
  {resort_id: 38, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490382943/lvk0haxgazdjyd1ysfdk.jpg", caption: nil},
  {resort_id: 38, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490382948/s7hqcoyoinfwqu5ivff3.jpg", caption: nil},
  {resort_id: 38, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490382952/lumhr14zajuruf5a5ppc.jpg", caption: nil},
  {resort_id: 37, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490390237/xnh6xlksiv32sd6xcrsz.jpg", caption: nil},
  {resort_id: 37, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490390243/diri0kw2igmdoykwtr21.jpg", caption: nil},
  {resort_id: 37, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490390248/x3h7lzupcoqvxkyrjxem.jpg", caption: nil},
  {resort_id: 36, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490390495/cw5w2khjl2lg8xuxpnbn.jpg", caption: nil},
  {resort_id: 36, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490390500/yscwjqu2yfo2htkgacf1.jpg", caption: nil},
  {resort_id: 36, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490390506/qxpozg0k02sqw6l33ncf.jpg", caption: nil},
  {resort_id: 34, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490390881/tfvm3jzps5zqlqnelq59.jpg", caption: nil},
  {resort_id: 34, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490390890/yuarsdd2irebji6iqvxi.jpg", caption: nil},
  {resort_id: 34, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490390895/fqlzbooabavtnnxf4afr.jpg", caption: nil},
  {resort_id: 33, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490391124/gap960wtjfapm96gp9qw.jpg", caption: nil},
  {resort_id: 33, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490391129/f8tk6todvapbox8egdal.jpg", caption: nil},
  {resort_id: 33, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490391133/cmp8ue1kle1nkay6b8tw.jpg", caption: nil},
  {resort_id: 35, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490391197/a7f0b4djieckyknwpuav.jpg", caption: nil},
  {resort_id: 35, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490391207/aqaeeo4d1oeu9pa8ogp9.jpg", caption: nil},
  {resort_id: 35, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490391212/cxra1cm7b2is94rsdmqj.jpg", caption: nil},
  {resort_id: 32, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490391334/djj8ww0bsiczfy46bubg.jpg", caption: nil},
  {resort_id: 32, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490391338/zgn1ozowkad7tqwagxuc.jpg", caption: nil},
  {resort_id: 32, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490391343/zxum7vsgfqvtydjoghyw.jpg", caption: nil},
  {resort_id: 31, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490391480/yu34tmjcvyrfjyic71wl.jpg", caption: nil},
  {resort_id: 31, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490391499/c5n8v07dczetbjcncdgc.jpg", caption: nil},
  {resort_id: 31, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490391507/awbvl72egnd0tlgbwysa.jpg", caption: nil},
  {resort_id: 30, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490391690/neu1qfd1d9nla21szo3s.jpg", caption: nil},
  {resort_id: 30, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490391698/machgwcx3y2ghwizq6kz.jpg", caption: nil},
  {resort_id: 29, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490391879/w4ko5fzuwviimptm6irr.jpg", caption: nil},
  {resort_id: 29, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490391918/qen4qetinb8ucvsl1hs4.jpg", caption: nil},
  {resort_id: 29, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392084/bwfj2l83ewtdl1c4av7v.jpg", caption: nil},
  {resort_id: 28, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392238/fbvsphdsfwspcr3lij1u.jpg", caption: nil},
  {resort_id: 28, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392243/ncluymmcaz5t8s1nkq1h.jpg", caption: nil},
  {resort_id: 28, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392247/o2ja5pje3ziktudmgdsv.jpg", caption: nil},
  {resort_id: 27, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392385/zqom1j2ocxazw4gebjep.jpg", caption: nil},
  {resort_id: 26, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392502/b6f2kckv1tpaedt5ogtu.jpg", caption: nil},
  {resort_id: 25, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392626/vhfttwk7s4hfi0l80ivv.jpg", caption: nil},
  {resort_id: 24, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392735/uzqgbtejfdxvdoyiqnjh.jpg", caption: nil},
  {resort_id: 23, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392904/cmys7rd5jfvbpiiu8hnq.jpg", caption: nil},
  {resort_id: 27, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392392/ebxh4qr1i3pdfu9kmako.jpg", caption: nil},
  {resort_id: 26, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392513/lqaxznntdrggegwfxzpc.jpg", caption: nil},
  {resort_id: 25, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392631/zmdp2ubpmax09rkfv5pn.jpg", caption: nil},
  {resort_id: 24, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392742/gbumg26myhlimpvxz940.jpg", caption: nil},
  {resort_id: 23, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392891/blyggvpijuaqkh50rhen.jpg", caption: nil},
  {resort_id: 27, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392398/msr3b4rtv7cebwlhgvyj.jpg", caption: nil},
  {resort_id: 26, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392519/edf6iq6a6qvjaxgsfaxv.jpg", caption: nil},
  {resort_id: 24, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392748/oaxxxnimonmtbrwgxj6m.jpg", caption: nil},
  {resort_id: 23, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392911/rakqinm4phxmjaeapjpd.jpg", caption: nil},
  {resort_id: 26, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392508/xqxrfolndmlxnixfldsi.jpg", caption: nil},
  {resort_id: 25, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392636/bjlfnu3jiuoatfbprfzl.jpg", caption: nil},
  {resort_id: 23, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490392898/wjmyjc5rz6ib6ix1xayq.jpg", caption: nil},
  {resort_id: 22, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490393110/egv3p1kldscbdukljvyx.jpg", caption: nil},
  {resort_id: 22, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490393123/wqpuy1njv0zojx44qb8n.jpg", caption: nil},
  {resort_id: 22, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490393131/hh5cinwlqc9shb4xaure.jpg", caption: nil},
  {resort_id: 21, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490393333/oremdlsrkgvmjtldbrfj.jpg", caption: nil},
  {resort_id: 21, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490393347/djv1f1mp7ul4axdtv8zi.jpg", caption: nil},
  {resort_id: 21, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490393355/kednyrwjuiga64l5d1wq.jpg", caption: nil},
  {resort_id: 20, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490393519/l4u7h5esjuj3i1dwnpdj.jpg", caption: nil},
  {resort_id: 20, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490393531/an3dnybzmppp2sawbiaj.jpg", caption: nil},
  {resort_id: 20, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490393541/hsj27rerfo5n0lhlztbo.jpg", caption: nil},
  {resort_id: 54, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490510593/vf75xnghmmwsejkkfj57.jpg", caption: nil},
  {resort_id: 54, user_id: 1, url: "https://res.cloudinary.com/dagjelvab/image/upload/v1490511939/bncpukh6jxudziamvcyc.jpg", caption: nil}
])
Review.create!([
  {resort_id: 7, user_id: 2, body: "A technical mountain with diverse terrain. Powder days should be spent in Mineral Basin and exploring tree runs. Pro tip: Get to the mountain really, really early when it snows or be caught in canyon traffic.", overall_rating: 4, basic_t_rating: 4, adv_t_rating: 5, amenities_rating: 3, services_rating: 5, value_rating: 3},
  {resort_id: 2, user_id: 1, body: "Best views in Lake Tahoe! There is some insane backcountry on the Nevada side down to the gondola, but make sure there's enough snow and good luck finding the exit or you could be walking...", overall_rating: 4, basic_t_rating: 5, adv_t_rating: 4, amenities_rating: 3, services_rating: 4, value_rating: 2},
  {resort_id: 2, user_id: 4, body: "Big, lots of terrain, lots of fun with fresh snow. Gets a bit packed with tourists and gapers in peak season, go on weekdays if possible", overall_rating: 3, basic_t_rating: 5, adv_t_rating: 3, amenities_rating: 2, services_rating: 1, value_rating: 1},
  {resort_id: 2, user_id: 3, body: "Choice views, rage approved.", overall_rating: 5, basic_t_rating: 3, adv_t_rating: 5, amenities_rating: 5, services_rating: 4, value_rating: 3},
  {resort_id: 1, user_id: 4, body: "Love the back bowls, some of the best spots in colorado on deep powder days.", overall_rating: 5, basic_t_rating: 4, adv_t_rating: 5, amenities_rating: 4, services_rating: 4, value_rating: 3},
  {resort_id: 1, user_id: 5, body: "Great terrain, lots to explore. Everything on the mountain is expensive so pack a lunch or don't forget your wallet. Parking is hard to find if you're driving out for day trip", overall_rating: 3, basic_t_rating: 4, adv_t_rating: 4, amenities_rating: 3, services_rating: 2, value_rating: 1},
  {resort_id: 1, user_id: 6, body: "Came looking for the K2, heard it was here. Nowhere to be found...", overall_rating: 2, basic_t_rating: 4, adv_t_rating: 3, amenities_rating: 3, services_rating: 1, value_rating: 1},
  {resort_id: 3, user_id: 3, body: "Big. Huge. Enormous. So much to ride. Village is a party at nights/weekends. Rage approved.", overall_rating: 5, basic_t_rating: 5, adv_t_rating: 5, amenities_rating: 4, services_rating: 5, value_rating: 4},
  {resort_id: 3, user_id: 6, body: "Best resort I've been to, the people working there are so nice and helpful! Lots to explore, not that expensvie compared to US resorts for the amount of terrain.", overall_rating: 5, basic_t_rating: 4, adv_t_rating: 3, amenities_rating: 5, services_rating: 5, value_rating: 5},
  {resort_id: 3, user_id: 7, body: "I don't really ski or snowboard but the views in the peak-to-peak gondola are amazing!", overall_rating: 4, basic_t_rating: 1, adv_t_rating: 1, amenities_rating: 5, services_rating: 5, value_rating: 4},
  {resort_id: 4, user_id: 8, body: "Best mountain in Tahoe for snowboarders. Lift farthest to the left has great tree runs, sidecountry, and natural half pipe. They get tons of snow!", overall_rating: 5, basic_t_rating: 4, adv_t_rating: 5, amenities_rating: 2, services_rating: 4, value_rating: 3},
  {resort_id: 4, user_id: 9, body: "Love the name. Kirkwoooood. My nephew is named Kirk. Wood is like the trees.", overall_rating: 4, basic_t_rating: 5, adv_t_rating: 5, amenities_rating: 3, services_rating: 3, value_rating: 4},
  {resort_id: 5, user_id: 9, body: "My home resort, ride it all the time. Jupiter is fun on powder days, best spot on the mtn. Lower half of front side gets crowded with newbies and ski school so stay away if you can.", overall_rating: 3, basic_t_rating: 5, adv_t_rating: 3, amenities_rating: 4, services_rating: 3, value_rating: 2},
  {resort_id: 5, user_id: 3, body: "I Ride Park City! Rage approved.", overall_rating: 4, basic_t_rating: 4, adv_t_rating: 4, amenities_rating: 3, services_rating: 3, value_rating: 4},
  {resort_id: 6, user_id: 1, body: "My favorite mountain in Utah. Not the biggest, but lots of fresh snow and not as crowded. TONS of tree runs everywhere, lots to explore between the runs. Parking lot is a bit annoying/gets crowded on weekends so try to get out early.", overall_rating: 5, basic_t_rating: 4, adv_t_rating: 5, amenities_rating: 3, services_rating: 2, value_rating: 5},
  {resort_id: 6, user_id: 4, body: "Fav place to chill. Western lift has sidecountry where you can find fresh tracks on most days with new snow.", overall_rating: 4, basic_t_rating: 4, adv_t_rating: 4, amenities_rating: 2, services_rating: 3, value_rating: 4},
  {resort_id: 7, user_id: 5, body: "The bird is the word. Fun stuff to ride but very/popular crowded, esp on weekends.", overall_rating: 4, basic_t_rating: 5, adv_t_rating: 5, amenities_rating: 4, services_rating: 3, value_rating: 3},
  {resort_id: 8, user_id: 6, body: "Best backcountry in the USA, hands down. Technical mountain, not recommended for beginners.", overall_rating: 5, basic_t_rating: 4, adv_t_rating: 5, amenities_rating: 4, services_rating: 4, value_rating: 3},
  {resort_id: 8, user_id: 7, body: "I just love the ol' western vibe in the town!", overall_rating: 4, basic_t_rating: 3, adv_t_rating: 3, amenities_rating: 5, services_rating: 5, value_rating: 5},
  {resort_id: 10, user_id: 2, body: "Great mountain for beginners to intermediate or people looking for big open runs and small crowds. Very bare bones local resort with few lodges, but they do call it powder mountain for a reason!", overall_rating: 3, basic_t_rating: 3, adv_t_rating: 1, amenities_rating: 1, services_rating: 5, value_rating: 5},
  {resort_id: 10, user_id: 8, body: "True to name, LOADS of powder. Worth the trip, you'll be the only one on the run.", overall_rating: 5, basic_t_rating: 5, adv_t_rating: 5, amenities_rating: 2, services_rating: 3, value_rating: 4},
  {resort_id: 11, user_id: 9, body: "Great mountain, great views, lots of variety in terrain. Expensive but worth it, at least on most days.", overall_rating: 4, basic_t_rating: 4, adv_t_rating: 3, amenities_rating: 4, services_rating: 4, value_rating: 2},
  {resort_id: 2, user_id: 9, body: "Love the views, plenty to ride. Fun for the whole family.", overall_rating: 4, basic_t_rating: 5, adv_t_rating: 3, amenities_rating: 4, services_rating: 5, value_rating: 2},
  {resort_id: 12, user_id: 8, body: "Steep, long, fast. Not for beginners. Longest run top to bottom is 9 miles! Bring your powder legs.", overall_rating: 5, basic_t_rating: 4, adv_t_rating: 5, amenities_rating: 2, services_rating: 3, value_rating: 5},
  {resort_id: 9, user_id: 7, body: "It's in Quebec, so they have great food. I love Canada!", overall_rating: 4, basic_t_rating: 2, adv_t_rating: 2, amenities_rating: 4, services_rating: 5, value_rating: 5},
  {resort_id: 5, user_id: 10, body: "Fun mountain with plenty to do for all ski levels. The cost of a lift ticket is pretty high, so if you prioritize a more of a luxurious experience and groomers this one is for you. There is definitely some awesome terrain that opens up with a ton of snow, but other resorts in the area normally have more.", overall_rating: 4, basic_t_rating: 5, adv_t_rating: 4, amenities_rating: 5, services_rating: 5, value_rating: 3},
  {resort_id: 6, user_id: 10, body: "This is a super fun mountain, especially for tree runs and park rats. Unfortunately it's gotten pretty crowded the past few years, but for the cost of a lift ticket it's a great value.", overall_rating: 5, basic_t_rating: 4, adv_t_rating: 5, amenities_rating: 4, services_rating: 4, value_rating: 5},
  {resort_id: 14, user_id: 10, body: "Solitude is mediocre during packed powder conditions, but on a powder day it's really hard to beat. It's never crowded. Check out Honeycomb canyon on a powder day and you won't be disappointed.", overall_rating: 4, basic_t_rating: 5, adv_t_rating: 4, amenities_rating: 4, services_rating: 4, value_rating: 5},
  {resort_id: 7, user_id: 10, body: "Snowbird offers amazing advanced terrain and spectacular views. However, the lift lines get out of control and even on powder days the runs are skied out really quickly. Since the ticket price is so high, I'd recommend going on a weekday to beat the lines and get your money's worth.", overall_rating: 4, basic_t_rating: 3, adv_t_rating: 5, amenities_rating: 5, services_rating: 5, value_rating: 1},
  {resort_id: 1, user_id: 10, body: "Vail has it all. Check out the back bowls on a powder day and investigate the trees on the front side for hidden powder stashes. It's a huge mountain with a ton to offer.", overall_rating: 4, basic_t_rating: 4, adv_t_rating: 5, amenities_rating: 5, services_rating: 5, value_rating: 3},
  {resort_id: 16, user_id: 10, body: "Mammoth has a lot of terrain for every type of rider. It's not nearly as crowded as other large resorts like Vail and Snowbird, and has great amenities and a variety of runs for all conditions.", overall_rating: 5, basic_t_rating: 5, adv_t_rating: 5, amenities_rating: 5, services_rating: 5, value_rating: 4},
  {resort_id: 2, user_id: 10, body: "Heavenly would be a much better mountain if it weren't always so overwhelmed with people. If you like to drink on the mountain and chill on groomers while regarding the views, you can definitely have a good time here.", overall_rating: 3, basic_t_rating: 4, adv_t_rating: 4, amenities_rating: 5, services_rating: 4, value_rating: 2},
  {resort_id: 4, user_id: 10, body: "When conditions are great Kirkwood is a shredder's dream. The left side of the mountain offers steeps, trees, and fresh lines.", overall_rating: 5, basic_t_rating: 5, adv_t_rating: 5, amenities_rating: 4, services_rating: 4, value_rating: 4},
  {resort_id: 15, user_id: 10, body: "There isn't a lot of elevation here but when Tahoe gets dumped on Northstar stays open where as other resorts close due to snow and wind conditions. It's a quiet, peaceful local feeling resort and great for the value.", overall_rating: 4, basic_t_rating: 4, adv_t_rating: 4, amenities_rating: 5, services_rating: 5, value_rating: 3},
  {resort_id: 12, user_id: 10, body: "This mountain is almost entirely vertical, with over 5500 feet elevation change from top to bottom. As far as tree runs go, Revelstoke is #1.  The views and terrain are incredible, but be careful as there are tons of unmarked cliffs. Definitely a more advanced mountain.", overall_rating: 5, basic_t_rating: 5, adv_t_rating: 5, amenities_rating: 4, services_rating: 5, value_rating: 5},
  {resort_id: 3, user_id: 10, body: "Whistler has something for everyone. Try not to go during holidays though because the lift lines get really long.", overall_rating: 5, basic_t_rating: 5, adv_t_rating: 4, amenities_rating: 5, services_rating: 5, value_rating: 4},
  {resort_id: 18, user_id: 10, body: "Visibility in the back bowls is really flat if when it's snowing, but if conditions are right you can choose the adventure that is perfect for you. This varied alpine terrain is great for advanced riders.", overall_rating: 4, basic_t_rating: 5, adv_t_rating: 4, amenities_rating: 4, services_rating: 5, value_rating: 4},
  {resort_id: 17, user_id: 10, body: "Wow, the reputation doesn't do this mountain justice. With 12 lifts, trees, a huge park, bowls, groomers, steeps, and views, I'm not sure what more you could ask for. Check out Goat's eye for fun tree runs.", overall_rating: 5, basic_t_rating: 5, adv_t_rating: 5, amenities_rating: 5, services_rating: 5, value_rating: 5},
  {resort_id: 12, user_id: 2, body: "My best powder days in North America have been here. I went mid-March 2017 and for two days, I had thigh high powder. I also really enjoy the mountain for the lack of crowds and the skill level seems to be above average. The tree runs here were also super playful. Not many lifts, but the runs are super long.", overall_rating: 4, basic_t_rating: 3, adv_t_rating: 5, amenities_rating: 2, services_rating: 5, value_rating: 5},
  {resort_id: 1, user_id: 12, body: "Awesome tree skiing.  The back bowels near China Bowl as well as the front side near Avanti has amazing runs with some space between the trees but mostly deep powder. If you aren't into trees then the back bowls offer wide-open runs with the ability to ski anywhere you see. Versatile and awe-inspiring mountain.", overall_rating: 5, basic_t_rating: 5, adv_t_rating: 5, amenities_rating: 5, services_rating: 5, value_rating: 3},
  {resort_id: 6, user_id: 12, body: "Amazing tree runs. Backcountry / side country options allow for more advanced riders to experience deep powder. Great access to the entire mountain. Beautiful sweeping views. An easy mountain to stay together as a group with riders of different levels. ", overall_rating: 4, basic_t_rating: 3, adv_t_rating: 4, amenities_rating: 2, services_rating: 5, value_rating: 5},
  {resort_id: 8, user_id: 12, body: "Great varied terrain. A lot of steep advanced terrain but also friendly beginner areas. The snow is light and fluffy and leads to some great skiing. Mountain is beautiful, with jagged rocks and canyons. ", overall_rating: 4, basic_t_rating: 4, adv_t_rating: 4, amenities_rating: 4, services_rating: 4, value_rating: 4},
  {resort_id: 30, user_id: 13, body: "gaper central; avoid at all costs", overall_rating: 1, basic_t_rating: 2, adv_t_rating: 1, amenities_rating: 1, services_rating: 3, value_rating: 1},
  {resort_id: 54, user_id: 13, body: "small and can be crowded but good for a day on the mountain. careful on the drive up - no guardrails or paved roads", overall_rating: 3, basic_t_rating: 3, adv_t_rating: 2, amenities_rating: 4, services_rating: 4, value_rating: 3},
  {resort_id: 30, user_id: 1, body: "Lol. This place is where I learned to snowboard! For that it holds a special place in my heart...but that's about all it has going for it . Its tiny, rarely has much snow, lift takes a while and usually has long lines. But its cheap and great place to learn if you're new!\n\nPS - There is no advanced terrain on this mountain. I gave a 1 for advanced terrain score only because there is no option for 0, who made this site anyway?", overall_rating: 2, basic_t_rating: 2, adv_t_rating: 1, amenities_rating: 1, services_rating: 2, value_rating: 4},
  {resort_id: 54, user_id: 1, body: "Great views, feels kinda cramped. Snow wasn't great when I visited so maybe not the best experience.", overall_rating: 3, basic_t_rating: 4, adv_t_rating: 2, amenities_rating: 2, services_rating: 3, value_rating: 2},
  {resort_id: 49, user_id: 1, body: "Went here with my brother in 2012, this was my favorite mountain in NZ! Beautiful, fun, and decent variety of terrain. Buildings/village at the base is pretty cool too.", overall_rating: 4, basic_t_rating: 4, adv_t_rating: 3, amenities_rating: 4, services_rating: 5, value_rating: 5},
  {resort_id: 24, user_id: 14, body: "Good, clean, Colorado fun. Just gotta get there somehow.", overall_rating: 4, basic_t_rating: 4, adv_t_rating: 5, amenities_rating: 3, services_rating: 4, value_rating: 3},
  {resort_id: 33, user_id: 3, body: "This is where Burton rides. Like them. Rage approved.", overall_rating: 5, basic_t_rating: 5, adv_t_rating: 3, amenities_rating: 5, services_rating: 4, value_rating: 5},
  {resort_id: 34, user_id: 15, body: "Austria is ok, but the mountains are big! Fun open snow fields to explore.", overall_rating: 4, basic_t_rating: 3, adv_t_rating: 5, amenities_rating: 5, services_rating: 3, value_rating: 4},
  {resort_id: 36, user_id: 16, body: "Big swiss resort. Hopefully have big swiss bank account.", overall_rating: 3, basic_t_rating: 5, adv_t_rating: 5, amenities_rating: 5, services_rating: 2, value_rating: 1},
  {resort_id: 38, user_id: 3, body: "Never been here but Davos...like game of thrones. Love that show. Rage approved.", overall_rating: 4, basic_t_rating: 3, adv_t_rating: 3, amenities_rating: 3, services_rating: 3, value_rating: 5},
  {resort_id: 40, user_id: 15, body: "Biggest resort I've ever been to! Could ride for weeks and not do same run. Open, not much trees. Fantastic food. Chalets for days.", overall_rating: 5, basic_t_rating: 5, adv_t_rating: 5, amenities_rating: 5, services_rating: 5, value_rating: 2},
  {resort_id: 41, user_id: 16, body: "Nothing like Italian food to fill you up after a long day of skiing.", overall_rating: 4, basic_t_rating: 3, adv_t_rating: 5, amenities_rating: 5, services_rating: 4, value_rating: 3},
  {resort_id: 39, user_id: 8, body: "This place has a name that's great to pronounce...and runs that are fun to ride too! Hehe...I'm great.", overall_rating: 3, basic_t_rating: 4, adv_t_rating: 3, amenities_rating: 4, services_rating: 4, value_rating: 4},
  {resort_id: 43, user_id: 7, body: "OMG the food in that picture looks so good. Cant wait to go here and chow down!", overall_rating: 4, basic_t_rating: 2, adv_t_rating: 1, amenities_rating: 5, services_rating: 5, value_rating: 5},
  {resort_id: 51, user_id: 9, body: "Best mountaintop views I've ever seen on a mountain. NZ is the best. The kiwis are so friendly, go visit!", overall_rating: 5, basic_t_rating: 5, adv_t_rating: 3, amenities_rating: 2, services_rating: 4, value_rating: 5},
  {resort_id: 47, user_id: 4, body: "Would love to visit here, I have lots of penguin friends in Japan who would slide with me!", overall_rating: 4, basic_t_rating: 2, adv_t_rating: 4, amenities_rating: 3, services_rating: 4, value_rating: 4},
  {resort_id: 23, user_id: 4, body: "Made lots of friends here!", overall_rating: 3, basic_t_rating: 5, adv_t_rating: 3, amenities_rating: 5, services_rating: 2, value_rating: 2},
  {resort_id: 23, user_id: 3, body: "Party at breck never stops! Rage approved.", overall_rating: 4, basic_t_rating: 3, adv_t_rating: 3, amenities_rating: 5, services_rating: 5, value_rating: 2},
  {resort_id: 25, user_id: 14, body: "Great trees on the back side. Lots of hidden gems!", overall_rating: 5, basic_t_rating: 3, adv_t_rating: 5, amenities_rating: 3, services_rating: 4, value_rating: 5}
])
User.create!([
  {username: "zestyyy", password_digest: "$2a$10$RhiL/gFQpSKYPEa1Jz9o5uybsDU6AqBlc.PJMboxS9DOX8O4cz31e", session_token: "-yTv5oOeDci3I0hL3mqLuQ", profile_pic_url: "http://res.cloudinary.com/dagjelvab/image/upload/v1490118437/girl-icon.jpg"},
  {username: "Skimax", password_digest: "$2a$10$qjLFNJXNk4cjXrvGffn2UezQRnx5hITDLrPR9rqNw9nGtft3Abkgi", session_token: "57LEJ-grp3OxC0t2AAp0xQ", profile_pic_url: "http://res.cloudinary.com/dagjelvab/image/upload/v1490118284/skier-profile.jpg"},
  {username: "Randy", password_digest: "$2a$10$lid/GZMhlag5FTrVvs5kouO61hBzp0lzGyhD9L3t9M7VLjRPIRp0i", session_token: "wvmOd57Sp9lGgfS4iOWdtg", profile_pic_url: "http://res.cloudinary.com/dagjelvab/image/upload/v1489967630/default-profile.png"},
  {username: "oreo", password_digest: "$2a$10$HOgpgcfaSpF9arihoSonqeG8r.AeNhozeoI0SZuCHTG/24n4iT3Om", session_token: "qM6OsrLOVuCyzbWo4k8_dQ", profile_pic_url: "http://res.cloudinary.com/dagjelvab/image/upload/v1490200976/114293-glowing-purple-neon-icon-sports-hobbies-people-snowboarder_fw87xr.png"},
  {username: "GuestUser", password_digest: "$2a$10$gLVRj2QH8DS22uCE4zRdiey10qLe/2DIVbP7jtw9wYNFm2O5AleMy", session_token: "XoQ0HEcIQAIuoDFQCKWgKg", profile_pic_url: "http://res.cloudinary.com/dagjelvab/image/upload/v1489967630/default-profile.png"},
  {username: "dellyBird", password_digest: "$2a$10$P7D4LLcqGfVA3aVz8AMyc.PwaxmqovdT4IHObgzjXQuIvPIjOua6e", session_token: "6QpYeXSHpxV3c_DL2761ZQ", profile_pic_url: "http://res.cloudinary.com/dagjelvab/image/upload/v1489967630/default-profile.png"},
  {username: "andhudhow", password_digest: "$2a$10$L8c8fsFGEjOZ0XnjtHO.TeNHerzVSdcMoVtpALBPK0qGlAQ3wtzeu", session_token: "L3zsOCMOvI4oUOmBjk9HLw", profile_pic_url: "http://res.cloudinary.com/dagjelvab/image/upload/v1489967630/default-profile.png"},
  {username: "EuroDude", password_digest: "$2a$10$I3KoltVNbe.9Rb0PfS4ya.sJ1CiLEd7gcztjHLJLx7L6HMHNWls3K", session_token: "5V7U6Vondh4-BLgixR1Jaw", profile_pic_url: "http://res.cloudinary.com/dagjelvab/image/upload/v1489967630/default-profile.png"},
  {username: "IamZeChalet", password_digest: "$2a$10$EnIKDjNDJUWhaT2RsH/rouFwbUlpIfRGY3IVRCz6vrYo2ma/4E83G", session_token: "nleLoSzvcUMoy_i_H2V6VQ", profile_pic_url: "http://res.cloudinary.com/dagjelvab/image/upload/v1489967630/default-profile.png"},
  {username: "powderHound", password_digest: "$2a$10$/oBVaaDsoT.RdJa4qregZOe0Z1rPcLnkWmUOo8UndGgGK/rsONC6S", session_token: "yD62zmq4_81Q7ej97YJpxA", profile_pic_url: "http://res.cloudinary.com/dagjelvab/image/upload/v1489967630/default-profile.png"},
  {username: "scott", password_digest: "$2a$10$fwRX/muMCvvAj54AdQyfIunf7jgjoDnUesnDfFSAhmLaRw4KU7mEO", session_token: "QeV-nlpz3pkvannEphf8nw", profile_pic_url: "http://res.cloudinary.com/dagjelvab/image/upload/v1489891110/boarder-icon.jpg"},
  {username: "kale", password_digest: "$2a$10$38dhAH0itdLreAPybFEXxu.mhgGw7x/hxoINfMLY49I2bZhQwPQqy", session_token: "LadgMP0vlUT6q4x2-NQ1nw", profile_pic_url: "http://res.cloudinary.com/dagjelvab/image/upload/v1489967630/default-profile.png"},
  {username: "doneSki", password_digest: "$2a$10$93e8hb4WGTErIPhE83Sdx.vEuXgJyhvGVPI4Xn52W7wRrp9GXGlk6", session_token: "FTfDH2W5hNVp1vj4_QF3IQ", profile_pic_url: "http://res.cloudinary.com/dagjelvab/image/upload/v1490118284/skier-profile.jpg"},
  {username: "penguin", password_digest: "$2a$10$.KxprzLUnkMnlUiO/dVJneXvyTISf6OiYqYKgOcdevfUcATvb2uTS", session_token: "1NRvyBsfMq83yMxv0eoG2w", profile_pic_url: "http://res.cloudinary.com/dagjelvab/image/upload/v1490118540/penguin-icon.jpg"},
  {username: "rage", password_digest: "$2a$10$TV85N6DDtoEf9g7zpxLkp.fRbhtZSn561rfeWdrV8oYh8CpTI3V9G", session_token: "tCQvKmOw7cviuSZEEBo-qQ", profile_pic_url: "http://res.cloudinary.com/dagjelvab/image/upload/v1489967630/default-profile.png"},
  {username: "myNameJeff", password_digest: "$2a$10$EbwtqOdTWNKBZqbz0mSb8OAC1noXAJJZp9MKxN7Ns/9nAFxrQJ4qq", session_token: "D2ImcaiGbZBiC17NSGFdHw", profile_pic_url: "http://res.cloudinary.com/dagjelvab/image/upload/v1489967630/default-profile.png"}
])
